// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxM4lvaWYfCXkmI3W0fPDT-S0PccHYHIk',
    appId: '1:595459834255:web:6682dbb6032ab272afcbfa',
    messagingSenderId: '595459834255',
    projectId: 'ashore-18e03',
    authDomain: 'ashore-18e03.firebaseapp.com',
    storageBucket: 'ashore-18e03.firebasestorage.app',
    measurementId: 'G-SKGWMVR9SW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaVEuz5vX5Aosw73N_3p0JB2Ir9DyDhs0',
    appId: '1:595459834255:android:2fc2876b9b7b3a48afcbfa',
    messagingSenderId: '595459834255',
    projectId: 'ashore-18e03',
    storageBucket: 'ashore-18e03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK-CErJ0EDBe0c5iT_vRu3Ci2H6NlsAOY',
    appId: '1:595459834255:ios:81156c070dd60f83afcbfa',
    messagingSenderId: '595459834255',
    projectId: 'ashore-18e03',
    storageBucket: 'ashore-18e03.firebasestorage.app',
    iosBundleId: 'com.example.ashore',
  );
}
